Update README.md
facebookresearch/fairscale pull request #244
Opened 2020-12-11 03:00 UTC by VitaliyLi

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?
Fixes # (issue).

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-12-11 04:03 UTC, Vittorio-Caggiano requested changes
should we have FairScale with capital F and S?

2020-12-11 22:28 UTC, min-xu-ai approved these changes
LGTM!

2020-12-11 22:28 UTC, min-xu-ai commented on README.md
> +fairscale is a PyTorch extension library for high performance and large scale training on one or multiple machines/nodes. This library extends basic PyTorch capabilities while adding new experimental
did we decide on some capitalization?

2020-12-16 00:37 UTC, min-xu-ai commented on README.md
> +fairscale is a PyTorch extension library for high performance and large scale training on one or multiple machines/nodes. This library extends basic PyTorch capabilities while adding new experimental
agreed with @Vittorio-Caggiano

2020-12-16 18:18 UTC, min-xu-ai commented
LGTM. I will merge it.

2020-12-16 18:18 UTC, merged